# Generated by Django 3.0 on 2019-12-26 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20191226_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='upload',
        ),
    ]
