# Generated by Django 3.0.1 on 2019-12-28 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20191228_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='upload',
            field=models.FileField(blank=True, upload_to='CompletedProjects/', verbose_name='Готовый проект'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.Category', verbose_name='Категория'),
        ),
    ]
