# Generated by Django 3.0.1 on 2020-01-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20191228_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['category'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterField(
            model_name='project',
            name='task',
            field=models.TextField(blank=True, verbose_name='Техническое задание'),
        ),
    ]
