# Generated by Django 3.0.2 on 2020-01-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20200103_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(blank=True, verbose_name='Дата публикации'),
        ),
    ]
