# Generated by Django 3.0.2 on 2020-01-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20200104_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(null=True, verbose_name='Дата публикации'),
        ),
    ]
