# Generated by Django 3.0.2 on 2020-01-06 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_auto_20200106_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='project',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.File', verbose_name='Готовый проект'),
        ),
    ]
