# Generated by Django 3.0.2 on 2020-01-10 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_auto_20200106_0337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Используемый язык')),
            ],
            options={
                'verbose_name': 'Используемый язык',
                'verbose_name_plural': 'Используемые языки',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.Language', verbose_name='Используемый язык'),
        ),
    ]
